library(GillespieSSA)
library(ggplot2)
x0 <- c(S=499,I=1,R=0)
a <- c("0.001*{S}*{I}","0.1*{I}")
nu <- matrix(c(-1,0,+1,-1,0,+1),nrow=3,byrow=T)
outssa <- ssa(x0,a,nu,tf=100,method="D")
outtau <- ssa(x0,a,nu,tf=100,method="ETL")
outotl <- ssa(x0,a,nu,tf=100,method="OTL")
sink('SIR_stat.txt')
cat("==========SSA=========="\n)
print(outssa$stats)
cat("==========ETL=========="\n)
print(outtau$stats)
cat("==========OTL=========="\n)
print(outotl$stats)
sink()
sink('SIR_ssa.dat')
print(outssa$data)
sink()
sink('SIR_tau.dat')
print(outtau$data)
sink()
sink('SIR_otl.dat')
print(outotl$data)
sink()