x0 <- c(Y1=1000,Y2=1000)
a <- c("10*{Y1}","0.01*{Y1}*{Y2}","10*{Y2}")
nu <- matrix(c(+1,-1,0,0,+1,-1),nrow=2,byrow=T)
outssa <- ssa(x0,a,nu,tf=100,method="D")
outtau <- ssa(x0,a,nu,tf=100,method="ETL")
outotl <- ssa(x0,a,nu,tf=100,method="OTL")
sink('LVM_stat.txt')
cat("==========SSA==========\n")
print(outssa$stats)
cat("==========ETL==========\n")
print(outtau$stats)
cat("==========OTL==========\n")
print(outotl$stats)
sink()
sink('LVM_ssa.dat')
print(outssa$data)
sink()
sink('LVM_tau.dat')
print(outtau$data)
sink()
sink('LVM_otl.dat')
print(outotl$data)
sink()